use std::collections::{BTreeSet, HashMap};
use std::fmt::{self, Write as FmtWrite};
use std::io::{self, Write as IoWrite};

use crate::cond::*;
use crate::expr::*;
use crate::nodes::*;

pub struct Generator {
    cellsize: u32,
    #[allow(dead_code)]
    debugging: bool,
}

impl Generator {
    pub fn new(cellsize: u32, debugging: bool) -> Self {
        Generator {
            cellsize,
            debugging,
        }
    }

    pub fn generate<W: IoWrite>(&self, node: &Node, out: &mut W) -> io::Result<()> {
        let mut state = GenState::new(self.cellsize);
        let mut body = String::new();
        state.write_node(&mut body, node).unwrap();

        writeln!(out, "/* generated by esotope-bfc */")?;
        writeln!(out, "#include <stdio.h>")?;
        writeln!(out, "#include <stdint.h>")?;
        if state.getcused {
            writeln!(out, "#define GETC() (fflush(stdout), fgetc(stdin))")?;
        }
        if state.putcused {
            writeln!(out, "#define PUTC(c) fputc(c, stdout)")?;
        }
        if state.putsused {
            writeln!(out, "#define PUTS(s) fwrite(s, 1, sizeof(s)-1, stdout)")?;
        }
        out.write_all(body.as_bytes())?;
        out.flush()
    }
}

struct GenState {
    cellsize: u32,
    nindents: usize,
    nextvars: HashMap<String, usize>,
    getcused: bool,
    putcused: bool,
    putsused: bool,
}

impl GenState {
    fn new(cellsize: u32) -> Self {
        GenState {
            cellsize,
            nindents: 0,
            nextvars: HashMap::new(),
            getcused: false,
            putcused: false,
            putsused: false,
        }
    }

    fn write_indent(&self, f: &mut dyn FmtWrite) -> fmt::Result {
        for _ in 0..self.nindents {
            f.write_char('\t')?;
        }
        Ok(())
    }

    fn writeln(&self, f: &mut dyn FmtWrite, line: fmt::Arguments<'_>) -> fmt::Result {
        self.write_indent(f)?;
        f.write_fmt(line)?;
        f.write_char('\n')
    }

    fn newvariable(&mut self, f: &mut dyn FmtWrite, prefix: &str) -> Result<String, fmt::Error> {
        let index = self.nextvars.entry(prefix.to_string()).or_insert(0);
        let name = format!("{prefix}{index}");
        *index += 1;
        self.writeln(f, format_args!("int {};", name))?;
        Ok(name)
    }

    fn write_node(&mut self, f: &mut dyn FmtWrite, node: &Node) -> fmt::Result {
        match node {
            Node::Nop => {}
            Node::SetMemory { offset, value } => {
                let delta = value - &Expr::mem(*offset);
                let full_len = {
                    let mut c = LenCounter(0);
                    write!(c, "p[{offset}] = {};", CExpr(value)).unwrap();
                    c.0
                };
                let short_len = {
                    let mut c = LenCounter(0);
                    write!(c, "{};", PRef(*offset, &delta)).unwrap();
                    c.0
                };
                if short_len < full_len {
                    self.writeln(f, format_args!("{};", PRef(*offset, &delta)))?;
                } else {
                    self.writeln(f, format_args!("p[{offset}] = {};", CExpr(value)))?;
                }
            }
            Node::MovePointer { offset } => {
                let adj = FormatAdjust("p", &Expr::Int(*offset));
                let s = adj.to_string();
                if !s.is_empty() {
                    self.writeln(f, format_args!("{s};"))?;
                }
            }
            Node::Input { offset } => {
                self.getcused = true;
                self.writeln(f, format_args!("p[{offset}] = GETC();"))?;
            }
            Node::Output { expr } => {
                self.putcused = true;
                self.writeln(f, format_args!("PUTC({});", CExpr(expr)))?;
            }
            Node::OutputConst { s } => {
                self.putsused = true;
                for chunk in split_lines_inclusive(s) {
                    self.writeln(f, format_args!("PUTS(\"{}\");", Addslashes(chunk)))?;
                }
            }
            Node::SeekMemory {
                target,
                stride,
                value,
            } => {
                let adj = FormatAdjust("p", &Expr::Int(*stride));
                self.writeln(f, format_args!("while (p[{target}] != {value}) {adj};"))?;
            }
            Node::Program { children } => {
                self.writeln(
                    f,
                    format_args!("static uint{}_t m[30000], *p = m;", self.cellsize),
                )?;
                self.writeln(f, format_args!("int main(void) {{"))?;
                self.nindents += 1;

                let mut returns = true;
                for child in children {
                    self.write_node(f, child)?;
                    returns &= child.returns();
                }
                if returns {
                    self.writeln(f, format_args!("return 0;"))?;
                }

                self.nindents -= 1;
                self.writeln(f, format_args!("}}"))?;
            }
            Node::If { cond, children } => {
                let adopted = adopt_cond(cond, self.cellsize);
                self.writeln(f, format_args!("if ({}) {{", CCond(&adopted)))?;
                self.nindents += 1;
                for child in children {
                    self.write_node(f, child)?;
                }
                self.nindents -= 1;
                self.writeln(f, format_args!("}}"))?;
            }
            Node::Repeat { count, children } => {
                let count_expr = if count.is_simple() || !matches!(count, Expr::Reference(_)) {
                    Expr::modulo(count.clone(), Expr::Int(1 << self.cellsize))
                } else {
                    count.clone()
                };
                let var = self.newvariable(f, "loopcnt")?;
                self.writeln(
                    f,
                    format_args!(
                        "for ({var} = {}; {var} > 0; --{var}) {{",
                        CExpr(&count_expr),
                    ),
                )?;
                self.nindents += 1;
                for child in children {
                    self.write_node(f, child)?;
                }
                self.nindents -= 1;
                self.writeln(f, format_args!("}}"))?;
            }
            Node::While { cond, children } => {
                if cond.is_always() && children.is_empty() {
                    self.writeln(f, format_args!("while (1); /* infinite loop */"))?;
                } else {
                    let adopted = adopt_cond(cond, self.cellsize);
                    self.writeln(f, format_args!("while ({}) {{", CCond(&adopted)))?;
                    self.nindents += 1;
                    for child in children {
                        self.write_node(f, child)?;
                    }
                    self.nindents -= 1;
                    self.writeln(f, format_args!("}}"))?;
                }
            }
        }
        Ok(())
    }
}

// --- Display wrappers that write directly to Formatter ---

struct CExpr<'a>(&'a Expr);
struct CExprPrec<'a>(&'a Expr, u32);
struct CCond<'a>(&'a Cond);
struct FormatAdjust<'a>(&'a str, &'a Expr);
struct PRef<'a>(i32, &'a Expr);
struct Addslashes<'a>(&'a [u8]);

impl fmt::Display for CExpr<'_> {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        CExprPrec(self.0, 0).fmt(f)
    }
}

impl fmt::Display for CExprPrec<'_> {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let CExprPrec(expr, prec) = *self;
        match expr {
            Expr::Int(v) => write!(f, "{v}"),
            Expr::Reference(offset) => write!(f, "p[{}]", CExpr(offset)),
            Expr::Linear(lin) => {
                if lin.terms.is_empty() && lin.constant == 0 {
                    return f.write_char('0');
                }
                let nparts = lin.terms.len() + if lin.constant != 0 { 1 } else { 0 };
                let need_paren = prec > 1 && nparts > 1;
                if need_paren {
                    f.write_char('(')?;
                }
                let mut first = true;
                for (v, k) in &lin.terms {
                    if first {
                        first = false;
                        match v {
                            -1 => write!(f, "-{}", CExprPrec(k, 1))?,
                            1 => CExprPrec(k, 1).fmt(f)?,
                            _ => write!(f, "{}*{}", v, CExprPrec(k, 1))?,
                        }
                    } else {
                        match v {
                            -1 => write!(f, "-{}", CExprPrec(k, 1))?,
                            1 => write!(f, "+{}", CExprPrec(k, 1))?,
                            _ => write!(f, "{v:+}*{}", CExprPrec(k, 1))?,
                        }
                    }
                }
                if lin.constant != 0 {
                    if first {
                        write!(f, "{}", lin.constant)?;
                    } else {
                        write!(f, "{:+}", lin.constant)?;
                    }
                }
                if need_paren {
                    f.write_char(')')?;
                }
                Ok(())
            }
            Expr::Multiply(factors) => {
                let need_paren = prec > 2 && factors.len() > 1;
                if need_paren {
                    f.write_char('(')?;
                }
                for (i, e) in factors.iter().enumerate() {
                    if i > 0 {
                        f.write_char('*')?;
                    }
                    CExprPrec(e, 2).fmt(f)?;
                }
                if need_paren {
                    f.write_char(')')?;
                }
                Ok(())
            }
            Expr::Division(l, r) | Expr::ExactDivision(l, r) => {
                if prec > 3 {
                    f.write_char('(')?;
                }
                write!(f, "{}/{}", CExprPrec(l, 2), CExprPrec(r, 2))?;
                if prec > 3 {
                    f.write_char(')')?;
                }
                Ok(())
            }
            Expr::Modulo(l, r) => {
                if prec > 3 {
                    f.write_char('(')?;
                }
                write!(f, "{}%{}", CExprPrec(l, 2), CExprPrec(r, 2))?;
                if prec > 3 {
                    f.write_char(')')?;
                }
                Ok(())
            }
        }
    }
}

impl fmt::Display for CCond<'_> {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self.0 {
            Cond::Always => f.write_char('1'),
            Cond::Never => f.write_char('0'),
            Cond::Equal(expr, 0) => write!(f, "!{}", CExpr(expr)),
            Cond::Equal(expr, v) => write!(f, "{} == {v}", CExpr(expr)),
            Cond::MemEqual(t, 0) => write!(f, "!p[{t}]"),
            Cond::MemEqual(t, v) => write!(f, "p[{t}] == {v}"),
            Cond::NotEqual(expr, 0) => CExpr(expr).fmt(f),
            Cond::NotEqual(expr, v) => write!(f, "{} != {v}", CExpr(expr)),
            Cond::MemNotEqual(t, 0) => write!(f, "p[{t}]"),
            Cond::MemNotEqual(t, v) => write!(f, "p[{t}] != {v}"),
            Cond::Range(expr, ranges) => {
                let e = CExpr(expr);
                if ranges.len() == 1 {
                    match ranges[0] {
                        (None, Some(mx)) => write!(f, "{e} <= {mx}"),
                        (Some(mn), None) => write!(f, "{mn} <= {e}"),
                        (Some(mn), Some(mx)) if mn == mx => write!(f, "{e} == {mn}"),
                        (Some(mn), Some(mx)) => write!(f, "({mn} <= {e} && {e} <= {mx})"),
                        (None, None) => f.write_char('1'),
                    }
                } else {
                    f.write_char('(')?;
                    for (i, &(min, max)) in ranges.iter().enumerate() {
                        if i > 0 {
                            f.write_str(" || ")?;
                        }
                        match (min, max) {
                            (None, Some(mx)) => write!(f, "{e} <= {mx}")?,
                            (Some(mn), None) => write!(f, "{mn} <= {e}")?,
                            (Some(mn), Some(mx)) if mn == mx => write!(f, "{e} == {mn}")?,
                            (Some(mn), Some(mx)) => write!(f, "({mn} <= {e} && {e} <= {mx})")?,
                            (None, None) => f.write_char('1')?,
                        }
                    }
                    f.write_char(')')
                }
            }
            Cond::Conjunction(clauses) => {
                f.write_char('(')?;
                for (i, c) in clauses.iter().enumerate() {
                    if i > 0 {
                        f.write_str(" && ")?;
                    }
                    CCond(c).fmt(f)?;
                }
                f.write_char(')')
            }
            Cond::Disjunction(clauses) => {
                f.write_char('(')?;
                for (i, c) in clauses.iter().enumerate() {
                    if i > 0 {
                        f.write_str(" || ")?;
                    }
                    CCond(c).fmt(f)?;
                }
                f.write_char(')')
            }
        }
    }
}

struct LenCounter(usize);

impl fmt::Write for LenCounter {
    fn write_str(&mut self, s: &str) -> fmt::Result {
        self.0 += s.len();
        Ok(())
    }
}

impl fmt::Display for FormatAdjust<'_> {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let FormatAdjust(refname, value) = *self;
        if let Some(v) = value.to_int() {
            match v {
                0 => return Ok(()),
                1 => return write!(f, "++{refname}"),
                -1 => return write!(f, "--{refname}"),
                _ => {}
            }
        }
        let neg = -value;
        let pos_len = {
            let mut c = LenCounter(0);
            write!(c, "{refname} += {}", CExpr(value)).unwrap();
            c.0
        };
        let neg_len = {
            let mut c = LenCounter(0);
            write!(c, "{refname} -= {}", CExpr(&neg)).unwrap();
            c.0
        };
        if neg_len < pos_len {
            write!(f, "{refname} -= {}", CExpr(&neg))
        } else {
            write!(f, "{refname} += {}", CExpr(value))
        }
    }
}

impl fmt::Display for PRef<'_> {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let PRef(offset, value) = *self;
        if let Some(v) = value.to_int() {
            match v {
                0 => return Ok(()),
                1 => return write!(f, "++p[{offset}]"),
                -1 => return write!(f, "--p[{offset}]"),
                _ => {}
            }
        }
        let neg = -value;
        let pos_len = {
            let mut c = LenCounter(0);
            write!(c, "p[{offset}] += {}", CExpr(value)).unwrap();
            c.0
        };
        let neg_len = {
            let mut c = LenCounter(0);
            write!(c, "p[{offset}] -= {}", CExpr(&neg)).unwrap();
            c.0
        };
        if neg_len < pos_len {
            write!(f, "p[{offset}] -= {}", CExpr(&neg))
        } else {
            write!(f, "p[{offset}] += {}", CExpr(value))
        }
    }
}

impl fmt::Display for Addslashes<'_> {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        for &b in self.0 {
            match b {
                0 => f.write_str("\\0")?,
                9 => f.write_str("\\t")?,
                10 => f.write_str("\\n")?,
                13 => f.write_str("\\r")?,
                34 => f.write_str("\\\"")?,
                39 => f.write_char('\'')?,
                92 => f.write_str("\\\\")?,
                32..=126 => f.write_char(b as char)?,
                _ => write!(f, "\\{b:03o}")?,
            }
        }
        Ok(())
    }
}

fn adopt_cond(cond: &Cond, cellsize: u32) -> Cond {
    match cond {
        Cond::Range(expr, ranges) => {
            let mut multiples = BTreeSet::new();
            for &(min, max) in ranges {
                if let Some(mn) = min {
                    multiples.insert(mn >> cellsize);
                }
                if let Some(mx) = max {
                    multiples.insert((mx - 1) >> cellsize);
                }
            }
            let mut realranges = vec![Cond::between(0, expr.clone(), (1i32 << cellsize) - 1)];
            for n in multiples {
                realranges.push(Cond::range(
                    expr + &Expr::Int(n << cellsize),
                    ranges.clone(),
                ));
            }
            Cond::conjunction(realranges)
        }
        Cond::Conjunction(clauses) => {
            Cond::conjunction(clauses.iter().map(|c| adopt_cond(c, cellsize)).collect())
        }
        Cond::Disjunction(clauses) => {
            Cond::disjunction(clauses.iter().map(|c| adopt_cond(c, cellsize)).collect())
        }
        _ => cond.clone(),
    }
}

fn split_lines_inclusive(s: &[u8]) -> Vec<&[u8]> {
    if s.is_empty() {
        return Vec::new();
    }
    let mut result = Vec::new();
    let mut start = 0;
    for (i, &b) in s.iter().enumerate() {
        if b == b'\n' {
            result.push(&s[start..=i]);
            start = i + 1;
        }
    }
    if start < s.len() {
        result.push(&s[start..]);
    }
    result
}

#[cfg(test)]
mod tests {
    use super::*;

    fn generate_c(node: &Node, cellsize: u32) -> String {
        let gen = Generator::new(cellsize, false);
        let mut out = Vec::new();
        gen.generate(node, &mut out).unwrap();
        String::from_utf8(out).unwrap()
    }

    #[test]
    fn empty_program() {
        let node = Node::Program { children: vec![] };
        let output = generate_c(&node, 8);
        assert!(output.contains("int main(void)"));
        assert!(output.contains("return 0;"));
        assert!(output.contains("uint8_t"));
    }

    #[test]
    fn cellsize_16() {
        let node = Node::Program { children: vec![] };
        let output = generate_c(&node, 16);
        assert!(output.contains("uint16_t"));
    }

    #[test]
    fn cellsize_32() {
        let node = Node::Program { children: vec![] };
        let output = generate_c(&node, 32);
        assert!(output.contains("uint32_t"));
    }

    #[test]
    fn set_memory_increment() {
        let node = Node::Program {
            children: vec![Node::adjust_memory_by(0, 1)],
        };
        let output = generate_c(&node, 8);
        assert!(output.contains("++p[0]"));
    }

    #[test]
    fn set_memory_decrement() {
        let node = Node::Program {
            children: vec![Node::adjust_memory_by(0, -1)],
        };
        let output = generate_c(&node, 8);
        assert!(output.contains("--p[0]"));
    }

    #[test]
    fn set_memory_absolute() {
        let node = Node::Program {
            children: vec![Node::SetMemory {
                offset: 0,
                value: Expr::Int(42),
            }],
        };
        let output = generate_c(&node, 8);
        assert!(output.contains("p[0] = 42;"));
    }

    #[test]
    fn move_pointer() {
        let node = Node::Program {
            children: vec![Node::MovePointer { offset: 3 }],
        };
        let output = generate_c(&node, 8);
        assert!(output.contains("p += 3;"));
    }

    #[test]
    fn input_generates_getc() {
        let node = Node::Program {
            children: vec![Node::Input { offset: 0 }],
        };
        let output = generate_c(&node, 8);
        assert!(output.contains("GETC()"));
        assert!(output.contains("#define GETC"));
    }

    #[test]
    fn output_generates_putc() {
        let node = Node::Program {
            children: vec![Node::Output { expr: Expr::mem(0) }],
        };
        let output = generate_c(&node, 8);
        assert!(output.contains("PUTC("));
        assert!(output.contains("#define PUTC"));
    }

    #[test]
    fn output_const_generates_puts() {
        let node = Node::Program {
            children: vec![Node::OutputConst {
                s: b"Hello".to_vec(),
            }],
        };
        let output = generate_c(&node, 8);
        assert!(output.contains("PUTS(\"Hello\")"));
        assert!(output.contains("#define PUTS"));
    }

    #[test]
    fn output_const_escaping() {
        let node = Node::Program {
            children: vec![Node::OutputConst {
                s: vec![0, 9, 10, 13, 34, 92],
            }],
        };
        let output = generate_c(&node, 8);
        assert!(output.contains("\\0"));
        assert!(output.contains("\\t"));
        assert!(output.contains("\\n"));
        assert!(output.contains("\\r"));
        assert!(output.contains("\\\""));
        assert!(output.contains("\\\\"));
    }

    #[test]
    fn while_loop() {
        let node = Node::Program {
            children: vec![Node::While {
                cond: Cond::MemNotEqual(0, 0),
                children: vec![Node::adjust_memory_by(0, -1)],
            }],
        };
        let output = generate_c(&node, 8);
        assert!(output.contains("while (p[0])"));
    }

    #[test]
    fn infinite_loop() {
        let node = Node::Program {
            children: vec![Node::While {
                cond: Cond::Always,
                children: vec![],
            }],
        };
        let output = generate_c(&node, 8);
        assert!(output.contains("while (1);"));
        assert!(!output.contains("return 0;"));
    }

    #[test]
    fn if_node() {
        let node = Node::Program {
            children: vec![Node::If {
                cond: Cond::MemNotEqual(0, 0),
                children: vec![Node::adjust_memory_by(1, 1)],
            }],
        };
        let output = generate_c(&node, 8);
        assert!(output.contains("if (p[0])"));
    }

    #[test]
    fn seek_memory() {
        let node = Node::Program {
            children: vec![Node::SeekMemory {
                target: 0,
                stride: 1,
                value: 0,
            }],
        };
        let output = generate_c(&node, 8);
        assert!(output.contains("while (p[0] != 0) ++p;"));
    }

    #[test]
    fn no_unused_macros() {
        let node = Node::Program {
            children: vec![Node::adjust_memory_by(0, 1)],
        };
        let output = generate_c(&node, 8);
        assert!(!output.contains("#define GETC"));
        assert!(!output.contains("#define PUTC"));
        assert!(!output.contains("#define PUTS"));
    }

    #[test]
    fn split_lines_inclusive_basic() {
        let lines = split_lines_inclusive(b"abc\ndef");
        assert_eq!(lines, vec![b"abc\n".as_ref(), b"def".as_ref()]);
    }

    #[test]
    fn split_lines_inclusive_empty() {
        assert!(split_lines_inclusive(b"").is_empty());
    }

    #[test]
    fn split_lines_inclusive_trailing_newline() {
        let lines = split_lines_inclusive(b"abc\n");
        assert_eq!(lines, vec![b"abc\n".as_ref()]);
    }

    #[test]
    fn addslashes_printable() {
        assert_eq!(Addslashes(b"ABC").to_string(), "ABC");
    }

    #[test]
    fn addslashes_special() {
        assert_eq!(Addslashes(b"\0").to_string(), "\\0");
        assert_eq!(Addslashes(b"\t").to_string(), "\\t");
        assert_eq!(Addslashes(b"\n").to_string(), "\\n");
        assert_eq!(Addslashes(b"\\").to_string(), "\\\\");
    }

    #[test]
    fn addslashes_nonprintable() {
        assert_eq!(Addslashes(&[128]).to_string(), "\\200");
        assert_eq!(Addslashes(&[255]).to_string(), "\\377");
    }

    #[test]
    fn cexpr_display() {
        assert_eq!(CExpr(&Expr::Int(42)).to_string(), "42");
        assert_eq!(CExpr(&Expr::mem(0)).to_string(), "p[0]");
    }

    #[test]
    fn ccond_display() {
        assert_eq!(CCond(&Cond::Always).to_string(), "1");
        assert_eq!(CCond(&Cond::Never).to_string(), "0");
        assert_eq!(CCond(&Cond::MemNotEqual(0, 0)).to_string(), "p[0]");
        assert_eq!(CCond(&Cond::MemEqual(0, 0)).to_string(), "!p[0]");
    }

    #[test]
    fn format_adjust_display() {
        assert_eq!(FormatAdjust("p", &Expr::Int(0)).to_string(), "");
        assert_eq!(FormatAdjust("p", &Expr::Int(1)).to_string(), "++p");
        assert_eq!(FormatAdjust("p", &Expr::Int(-1)).to_string(), "--p");
        assert_eq!(FormatAdjust("p[0]", &Expr::Int(3)).to_string(), "p[0] += 3");
    }
}
