use std::collections::{BTreeMap, BTreeSet, HashMap};
use std::fmt::{self, Write as FmtWrite};
use std::io::{self, Write as IoWrite};

use crate::cond::*;
use crate::expr::*;
use crate::nodes::*;

pub struct Generator {
    cellsize: u32,
    #[allow(dead_code)]
    debugging: bool,
    used_cells: Option<BTreeSet<i32>>,
    lower_to_vars: bool,
}

impl Generator {
    pub fn new(
        cellsize: u32,
        debugging: bool,
        used_cells: Option<&BTreeSet<i32>>,
        lower_to_vars: bool,
    ) -> Self {
        Generator {
            cellsize,
            debugging,
            used_cells: used_cells.cloned(),
            lower_to_vars,
        }
    }

    pub fn generate<W: IoWrite>(&self, node: &Node, out: &mut W) -> io::Result<()> {
        let var_mode = if self.lower_to_vars {
            self.used_cells.as_ref().map(|cells| {
                let cell_names: BTreeMap<i32, String> = cells
                    .iter()
                    .enumerate()
                    .map(|(i, &cell)| (cell, format!("c{i}")))
                    .collect();
                VarMode {
                    cell_names,
                    ptr_offset: 0,
                }
            })
        } else {
            None
        };

        let mut state = GenState::new(self.cellsize, &self.used_cells, var_mode);
        let mut body = String::new();
        state.write_node(&mut body, node).unwrap();

        writeln!(out, "/* generated by esotope-bfc */")?;
        writeln!(out, "#include <stdio.h>")?;
        writeln!(out, "#include <stdint.h>")?;
        if state.getcused {
            writeln!(out, "#define GETC() (fflush(stdout), fgetc(stdin))")?;
        }
        if state.putcused {
            writeln!(out, "#define PUTC(c) fputc(c, stdout)")?;
        }
        if state.putsused {
            writeln!(out, "#define PUTS(s) fwrite(s, 1, sizeof(s)-1, stdout)")?;
        }
        out.write_all(body.as_bytes())?;
        out.flush()
    }
}

struct VarMode {
    cell_names: BTreeMap<i32, String>,
    ptr_offset: i32,
}

struct GenState<'a> {
    cellsize: u32,
    nindents: usize,
    nextvars: HashMap<String, usize>,
    getcused: bool,
    putcused: bool,
    putsused: bool,
    used_cells: &'a Option<BTreeSet<i32>>,
    var_mode: Option<VarMode>,
}

impl<'a> GenState<'a> {
    fn new(
        cellsize: u32,
        used_cells: &'a Option<BTreeSet<i32>>,
        var_mode: Option<VarMode>,
    ) -> Self {
        GenState {
            cellsize,
            nindents: 0,
            nextvars: HashMap::new(),
            getcused: false,
            putcused: false,
            putsused: false,
            used_cells,
            var_mode,
        }
    }

    fn write_indent(&self, f: &mut dyn FmtWrite) -> fmt::Result {
        for _ in 0..self.nindents {
            f.write_char('\t')?;
        }
        Ok(())
    }

    fn writeln(&self, f: &mut dyn FmtWrite, line: fmt::Arguments<'_>) -> fmt::Result {
        self.write_indent(f)?;
        f.write_fmt(line)?;
        f.write_char('\n')
    }

    fn newvariable(&mut self, f: &mut dyn FmtWrite, prefix: &str) -> Result<String, fmt::Error> {
        let index = self.nextvars.entry(prefix.to_string()).or_insert(0);
        let name = format!("{prefix}{index}");
        *index += 1;
        self.writeln(f, format_args!("int {};", name))?;
        Ok(name)
    }

    fn format_cell(&self, offset: i32) -> String {
        if let Some(ref vm) = self.var_mode {
            let abs = vm.ptr_offset + offset;
            vm.cell_names[&abs].clone()
        } else {
            format!("p[{offset}]")
        }
    }

    fn format_expr(&self, expr: &Expr) -> String {
        if let Some(ref vm) = self.var_mode {
            format_var_expr(expr, 0, vm)
        } else {
            CExpr(expr).to_string()
        }
    }

    fn format_cond(&self, cond: &Cond) -> String {
        let adopted = adopt_cond(cond, self.cellsize);
        if let Some(ref vm) = self.var_mode {
            format_var_cond(&adopted, vm)
        } else {
            CCond(&adopted).to_string()
        }
    }

    fn format_set_memory(&self, offset: i32, value: &Expr) -> String {
        let cell = self.format_cell(offset);
        let val_str = self.format_expr(value);
        let delta = value - &Expr::mem(offset);

        let full = format!("{cell} = {val_str};");

        if let Some(ref vm) = self.var_mode {
            let delta_str = format_var_adjust(&cell, &delta, vm);
            if delta_str.is_empty() {
                return String::new();
            }
            let short = format!("{delta_str};");
            if short.len() < full.len() {
                short
            } else {
                full
            }
        } else {
            let short_len = {
                let mut c = LenCounter(0);
                write!(c, "{};", PRef(offset, &delta)).unwrap();
                c.0
            };
            if short_len < full.len() {
                format!("{};", PRef(offset, &delta))
            } else {
                full
            }
        }
    }

    fn write_node(&mut self, f: &mut dyn FmtWrite, node: &Node) -> fmt::Result {
        match node {
            Node::Nop => {}
            Node::SetMemory { offset, value } => {
                let s = self.format_set_memory(*offset, value);
                if !s.is_empty() {
                    self.writeln(f, format_args!("{s}"))?;
                }
            }
            Node::MovePointer { offset } => {
                if let Some(ref mut vm) = self.var_mode {
                    vm.ptr_offset += offset;
                } else {
                    let adj = FormatAdjust("p", &Expr::Int(*offset));
                    let s = adj.to_string();
                    if !s.is_empty() {
                        self.writeln(f, format_args!("{s};"))?;
                    }
                }
            }
            Node::Input { offset } => {
                self.getcused = true;
                let cell = self.format_cell(*offset);
                self.writeln(f, format_args!("{cell} = GETC();"))?;
            }
            Node::Output { expr } => {
                self.putcused = true;
                let e = self.format_expr(expr);
                self.writeln(f, format_args!("PUTC({e});"))?;
            }
            Node::OutputConst { s } => {
                self.putsused = true;
                for chunk in split_lines_inclusive(s) {
                    self.writeln(f, format_args!("PUTS(\"{}\");", Addslashes(chunk)))?;
                }
            }
            Node::SeekMemory {
                target,
                stride,
                value,
            } => {
                let adj = FormatAdjust("p", &Expr::Int(*stride));
                self.writeln(f, format_args!("while (p[{target}] != {value}) {adj};"))?;
            }
            Node::Program { children } => {
                if let Some(ref vm) = self.var_mode {
                    if vm.cell_names.is_empty() {
                        self.writeln(f, format_args!("int main(void) {{"))?;
                    } else {
                        let decls: Vec<String> = vm
                            .cell_names
                            .values()
                            .map(|name| format!("{name} = 0"))
                            .collect();
                        self.writeln(
                            f,
                            format_args!("static uint{}_t {};", self.cellsize, decls.join(", ")),
                        )?;
                        self.writeln(f, format_args!("int main(void) {{"))?;
                    }
                } else if let Some(ref cells) = self.used_cells {
                    let size = if cells.is_empty() {
                        1
                    } else {
                        let min = *cells.iter().next().unwrap();
                        let max = *cells.iter().next_back().unwrap();
                        (max - min + 1) as u32
                    };
                    if cells.is_empty() || *cells.iter().next().unwrap() >= 0 {
                        let arr_size = if cells.is_empty() {
                            1
                        } else {
                            (*cells.iter().next_back().unwrap() + 1) as u32
                        };
                        self.writeln(
                            f,
                            format_args!("static uint{}_t m[{}], *p = m;", self.cellsize, arr_size),
                        )?;
                    } else {
                        let min = *cells.iter().next().unwrap();
                        self.writeln(
                            f,
                            format_args!(
                                "static uint{}_t m[{}], *p = m + {};",
                                self.cellsize, size, -min
                            ),
                        )?;
                    }
                    self.writeln(f, format_args!("int main(void) {{"))?;
                } else {
                    self.writeln(
                        f,
                        format_args!("static uint{}_t m[30000], *p = m;", self.cellsize),
                    )?;
                    self.writeln(f, format_args!("int main(void) {{"))?;
                };
                self.nindents += 1;

                let mut returns = true;
                for child in children {
                    self.write_node(f, child)?;
                    returns &= child.returns();
                }
                if returns {
                    self.writeln(f, format_args!("return 0;"))?;
                }

                self.nindents -= 1;
                self.writeln(f, format_args!("}}"))?;
            }
            Node::If { cond, children } => {
                let cond_str = self.format_cond(cond);
                self.writeln(f, format_args!("if ({cond_str}) {{"))?;
                self.nindents += 1;
                for child in children {
                    self.write_node(f, child)?;
                }
                self.nindents -= 1;
                self.writeln(f, format_args!("}}"))?;
            }
            Node::Repeat { count, children } => {
                let count_expr = if count.is_simple() || !matches!(count, Expr::Reference(_)) {
                    Expr::modulo(count.clone(), Expr::Int(1 << self.cellsize))
                } else {
                    count.clone()
                };
                let var = self.newvariable(f, "loopcnt")?;
                let ce = self.format_expr(&count_expr);
                self.writeln(f, format_args!("for ({var} = {ce}; {var} > 0; --{var}) {{"))?;
                self.nindents += 1;
                for child in children {
                    self.write_node(f, child)?;
                }
                self.nindents -= 1;
                self.writeln(f, format_args!("}}"))?;
            }
            Node::While { cond, children } => {
                if cond.is_always() && children.is_empty() {
                    self.writeln(f, format_args!("while (1); /* infinite loop */"))?;
                } else {
                    let cond_str = self.format_cond(cond);
                    self.writeln(f, format_args!("while ({cond_str}) {{"))?;
                    self.nindents += 1;
                    for child in children {
                        self.write_node(f, child)?;
                    }
                    self.nindents -= 1;
                    self.writeln(f, format_args!("}}"))?;
                }
            }
        }
        Ok(())
    }
}

// --- Display wrappers that write directly to Formatter ---

struct CExpr<'a>(&'a Expr);
struct CExprPrec<'a>(&'a Expr, u32);
struct CCond<'a>(&'a Cond);
struct FormatAdjust<'a>(&'a str, &'a Expr);
struct PRef<'a>(i32, &'a Expr);
struct Addslashes<'a>(&'a [u8]);

impl fmt::Display for CExpr<'_> {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        CExprPrec(self.0, 0).fmt(f)
    }
}

impl fmt::Display for CExprPrec<'_> {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let CExprPrec(expr, prec) = *self;
        match expr {
            Expr::Int(v) => write!(f, "{v}"),
            Expr::Reference(offset) => write!(f, "p[{}]", CExpr(offset)),
            Expr::Linear(lin) => {
                if lin.terms.is_empty() && lin.constant == 0 {
                    return f.write_char('0');
                }
                let nparts = lin.terms.len() + if lin.constant != 0 { 1 } else { 0 };
                let need_paren = prec > 1 && nparts > 1;
                if need_paren {
                    f.write_char('(')?;
                }
                let mut first = true;
                for (v, k) in &lin.terms {
                    if first {
                        first = false;
                        match v {
                            -1 => write!(f, "-{}", CExprPrec(k, 1))?,
                            1 => CExprPrec(k, 1).fmt(f)?,
                            _ => write!(f, "{}*{}", v, CExprPrec(k, 1))?,
                        }
                    } else {
                        match v {
                            -1 => write!(f, "-{}", CExprPrec(k, 1))?,
                            1 => write!(f, "+{}", CExprPrec(k, 1))?,
                            _ => write!(f, "{v:+}*{}", CExprPrec(k, 1))?,
                        }
                    }
                }
                if lin.constant != 0 {
                    if first {
                        write!(f, "{}", lin.constant)?;
                    } else {
                        write!(f, "{:+}", lin.constant)?;
                    }
                }
                if need_paren {
                    f.write_char(')')?;
                }
                Ok(())
            }
            Expr::Multiply(factors) => {
                let need_paren = prec > 2 && factors.len() > 1;
                if need_paren {
                    f.write_char('(')?;
                }
                for (i, e) in factors.iter().enumerate() {
                    if i > 0 {
                        f.write_char('*')?;
                    }
                    CExprPrec(e, 2).fmt(f)?;
                }
                if need_paren {
                    f.write_char(')')?;
                }
                Ok(())
            }
            Expr::Division(l, r) | Expr::ExactDivision(l, r) => {
                if prec > 3 {
                    f.write_char('(')?;
                }
                write!(f, "{}/{}", CExprPrec(l, 2), CExprPrec(r, 2))?;
                if prec > 3 {
                    f.write_char(')')?;
                }
                Ok(())
            }
            Expr::Modulo(l, r) => {
                if prec > 3 {
                    f.write_char('(')?;
                }
                write!(f, "{}%{}", CExprPrec(l, 2), CExprPrec(r, 2))?;
                if prec > 3 {
                    f.write_char(')')?;
                }
                Ok(())
            }
        }
    }
}

impl fmt::Display for CCond<'_> {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self.0 {
            Cond::Always => f.write_char('1'),
            Cond::Never => f.write_char('0'),
            Cond::Equal(expr, 0) => write!(f, "!{}", CExpr(expr)),
            Cond::Equal(expr, v) => write!(f, "{} == {v}", CExpr(expr)),
            Cond::MemEqual(t, 0) => write!(f, "!p[{t}]"),
            Cond::MemEqual(t, v) => write!(f, "p[{t}] == {v}"),
            Cond::NotEqual(expr, 0) => CExpr(expr).fmt(f),
            Cond::NotEqual(expr, v) => write!(f, "{} != {v}", CExpr(expr)),
            Cond::MemNotEqual(t, 0) => write!(f, "p[{t}]"),
            Cond::MemNotEqual(t, v) => write!(f, "p[{t}] != {v}"),
            Cond::Range(expr, ranges) => {
                let e = CExpr(expr);
                if ranges.len() == 1 {
                    match ranges[0] {
                        (None, Some(mx)) => write!(f, "{e} <= {mx}"),
                        (Some(mn), None) => write!(f, "{mn} <= {e}"),
                        (Some(mn), Some(mx)) if mn == mx => write!(f, "{e} == {mn}"),
                        (Some(mn), Some(mx)) => write!(f, "({mn} <= {e} && {e} <= {mx})"),
                        (None, None) => f.write_char('1'),
                    }
                } else {
                    f.write_char('(')?;
                    for (i, &(min, max)) in ranges.iter().enumerate() {
                        if i > 0 {
                            f.write_str(" || ")?;
                        }
                        match (min, max) {
                            (None, Some(mx)) => write!(f, "{e} <= {mx}")?,
                            (Some(mn), None) => write!(f, "{mn} <= {e}")?,
                            (Some(mn), Some(mx)) if mn == mx => write!(f, "{e} == {mn}")?,
                            (Some(mn), Some(mx)) => write!(f, "({mn} <= {e} && {e} <= {mx})")?,
                            (None, None) => f.write_char('1')?,
                        }
                    }
                    f.write_char(')')
                }
            }
            Cond::Conjunction(clauses) => {
                f.write_char('(')?;
                for (i, c) in clauses.iter().enumerate() {
                    if i > 0 {
                        f.write_str(" && ")?;
                    }
                    CCond(c).fmt(f)?;
                }
                f.write_char(')')
            }
            Cond::Disjunction(clauses) => {
                f.write_char('(')?;
                for (i, c) in clauses.iter().enumerate() {
                    if i > 0 {
                        f.write_str(" || ")?;
                    }
                    CCond(c).fmt(f)?;
                }
                f.write_char(')')
            }
        }
    }
}

struct LenCounter(usize);

impl fmt::Write for LenCounter {
    fn write_str(&mut self, s: &str) -> fmt::Result {
        self.0 += s.len();
        Ok(())
    }
}

impl fmt::Display for FormatAdjust<'_> {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let FormatAdjust(refname, value) = *self;
        if let Some(v) = value.to_int() {
            match v {
                0 => return Ok(()),
                1 => return write!(f, "++{refname}"),
                -1 => return write!(f, "--{refname}"),
                _ => {}
            }
        }
        let neg = -value;
        let pos_len = {
            let mut c = LenCounter(0);
            write!(c, "{refname} += {}", CExpr(value)).unwrap();
            c.0
        };
        let neg_len = {
            let mut c = LenCounter(0);
            write!(c, "{refname} -= {}", CExpr(&neg)).unwrap();
            c.0
        };
        if neg_len < pos_len {
            write!(f, "{refname} -= {}", CExpr(&neg))
        } else {
            write!(f, "{refname} += {}", CExpr(value))
        }
    }
}

impl fmt::Display for PRef<'_> {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let PRef(offset, value) = *self;
        if let Some(v) = value.to_int() {
            match v {
                0 => return Ok(()),
                1 => return write!(f, "++p[{offset}]"),
                -1 => return write!(f, "--p[{offset}]"),
                _ => {}
            }
        }
        let neg = -value;
        let pos_len = {
            let mut c = LenCounter(0);
            write!(c, "p[{offset}] += {}", CExpr(value)).unwrap();
            c.0
        };
        let neg_len = {
            let mut c = LenCounter(0);
            write!(c, "p[{offset}] -= {}", CExpr(&neg)).unwrap();
            c.0
        };
        if neg_len < pos_len {
            write!(f, "p[{offset}] -= {}", CExpr(&neg))
        } else {
            write!(f, "p[{offset}] += {}", CExpr(value))
        }
    }
}

impl fmt::Display for Addslashes<'_> {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        for &b in self.0 {
            match b {
                0 => f.write_str("\\0")?,
                9 => f.write_str("\\t")?,
                10 => f.write_str("\\n")?,
                13 => f.write_str("\\r")?,
                34 => f.write_str("\\\"")?,
                39 => f.write_char('\'')?,
                92 => f.write_str("\\\\")?,
                32..=126 => f.write_char(b as char)?,
                _ => write!(f, "\\{b:03o}")?,
            }
        }
        Ok(())
    }
}

fn format_var_expr(expr: &Expr, prec: u32, vm: &VarMode) -> String {
    match expr {
        Expr::Int(v) => format!("{v}"),
        Expr::Reference(offset) => {
            let off = offset.to_int().unwrap();
            let abs = vm.ptr_offset + off;
            vm.cell_names[&abs].clone()
        }
        Expr::Linear(lin) => {
            if lin.terms.is_empty() && lin.constant == 0 {
                return "0".to_string();
            }
            let nparts = lin.terms.len() + if lin.constant != 0 { 1 } else { 0 };
            let need_paren = prec > 1 && nparts > 1;
            let mut s = String::new();
            if need_paren {
                s.push('(');
            }
            let mut first = true;
            for (v, k) in &lin.terms {
                let ks = format_var_expr(k, 1, vm);
                if first {
                    first = false;
                    match v {
                        -1 => write!(s, "-{ks}").unwrap(),
                        1 => s.push_str(&ks),
                        _ => write!(s, "{v}*{ks}").unwrap(),
                    }
                } else {
                    match v {
                        -1 => write!(s, "-{ks}").unwrap(),
                        1 => write!(s, "+{ks}").unwrap(),
                        _ => write!(s, "{v:+}*{ks}").unwrap(),
                    }
                }
            }
            if lin.constant != 0 {
                if first {
                    write!(s, "{}", lin.constant).unwrap();
                } else {
                    write!(s, "{:+}", lin.constant).unwrap();
                }
            }
            if need_paren {
                s.push(')');
            }
            s
        }
        Expr::Multiply(factors) => {
            let need_paren = prec > 2 && factors.len() > 1;
            let mut s = String::new();
            if need_paren {
                s.push('(');
            }
            for (i, e) in factors.iter().enumerate() {
                if i > 0 {
                    s.push('*');
                }
                s.push_str(&format_var_expr(e, 2, vm));
            }
            if need_paren {
                s.push(')');
            }
            s
        }
        Expr::Division(l, r) | Expr::ExactDivision(l, r) => {
            let mut s = String::new();
            if prec > 3 {
                s.push('(');
            }
            write!(
                s,
                "{}/{}",
                format_var_expr(l, 2, vm),
                format_var_expr(r, 2, vm)
            )
            .unwrap();
            if prec > 3 {
                s.push(')');
            }
            s
        }
        Expr::Modulo(l, r) => {
            let mut s = String::new();
            if prec > 3 {
                s.push('(');
            }
            write!(
                s,
                "{}%{}",
                format_var_expr(l, 2, vm),
                format_var_expr(r, 2, vm)
            )
            .unwrap();
            if prec > 3 {
                s.push(')');
            }
            s
        }
    }
}

fn format_var_cond(cond: &Cond, vm: &VarMode) -> String {
    match cond {
        Cond::Always => "1".to_string(),
        Cond::Never => "0".to_string(),
        Cond::Equal(expr, 0) => format!("!{}", format_var_expr(expr, 0, vm)),
        Cond::Equal(expr, v) => format!("{} == {v}", format_var_expr(expr, 0, vm)),
        Cond::NotEqual(expr, 0) => format_var_expr(expr, 0, vm),
        Cond::NotEqual(expr, v) => format!("{} != {v}", format_var_expr(expr, 0, vm)),
        Cond::MemEqual(t, 0) => {
            let abs = vm.ptr_offset + t;
            format!("!{}", vm.cell_names[&abs])
        }
        Cond::MemEqual(t, v) => {
            let abs = vm.ptr_offset + t;
            format!("{} == {v}", vm.cell_names[&abs])
        }
        Cond::MemNotEqual(t, 0) => {
            let abs = vm.ptr_offset + t;
            vm.cell_names[&abs].clone()
        }
        Cond::MemNotEqual(t, v) => {
            let abs = vm.ptr_offset + t;
            format!("{} != {v}", vm.cell_names[&abs])
        }
        Cond::Range(expr, ranges) => {
            let e = format_var_expr(expr, 0, vm);
            if ranges.len() == 1 {
                match ranges[0] {
                    (None, Some(mx)) => format!("{e} <= {mx}"),
                    (Some(mn), None) => format!("{mn} <= {e}"),
                    (Some(mn), Some(mx)) if mn == mx => format!("{e} == {mn}"),
                    (Some(mn), Some(mx)) => format!("({mn} <= {e} && {e} <= {mx})"),
                    (None, None) => "1".to_string(),
                }
            } else {
                let mut s = "(".to_string();
                for (i, &(min, max)) in ranges.iter().enumerate() {
                    if i > 0 {
                        s.push_str(" || ");
                    }
                    match (min, max) {
                        (None, Some(mx)) => write!(s, "{e} <= {mx}").unwrap(),
                        (Some(mn), None) => write!(s, "{mn} <= {e}").unwrap(),
                        (Some(mn), Some(mx)) if mn == mx => write!(s, "{e} == {mn}").unwrap(),
                        (Some(mn), Some(mx)) => write!(s, "({mn} <= {e} && {e} <= {mx})").unwrap(),
                        (None, None) => s.push('1'),
                    }
                }
                s.push(')');
                s
            }
        }
        Cond::Conjunction(clauses) => {
            let mut s = "(".to_string();
            for (i, c) in clauses.iter().enumerate() {
                if i > 0 {
                    s.push_str(" && ");
                }
                s.push_str(&format_var_cond(c, vm));
            }
            s.push(')');
            s
        }
        Cond::Disjunction(clauses) => {
            let mut s = "(".to_string();
            for (i, c) in clauses.iter().enumerate() {
                if i > 0 {
                    s.push_str(" || ");
                }
                s.push_str(&format_var_cond(c, vm));
            }
            s.push(')');
            s
        }
    }
}

fn format_var_adjust(refname: &str, value: &Expr, vm: &VarMode) -> String {
    if let Some(v) = value.to_int() {
        match v {
            0 => return String::new(),
            1 => return format!("++{refname}"),
            -1 => return format!("--{refname}"),
            _ => {}
        }
    }
    let neg = -value;
    let vs = format_var_expr(value, 0, vm);
    let ns = format_var_expr(&neg, 0, vm);
    let pos = format!("{refname} += {vs}");
    let negs = format!("{refname} -= {ns}");
    if negs.len() < pos.len() {
        negs
    } else {
        pos
    }
}

fn adopt_cond(cond: &Cond, cellsize: u32) -> Cond {
    match cond {
        Cond::Range(expr, ranges) => {
            let mut multiples = BTreeSet::new();
            for &(min, max) in ranges {
                if let Some(mn) = min {
                    multiples.insert(mn >> cellsize);
                }
                if let Some(mx) = max {
                    multiples.insert((mx - 1) >> cellsize);
                }
            }
            let mut realranges = vec![Cond::between(0, expr.clone(), (1i32 << cellsize) - 1)];
            for n in multiples {
                realranges.push(Cond::range(
                    expr + &Expr::Int(n << cellsize),
                    ranges.clone(),
                ));
            }
            Cond::conjunction(realranges)
        }
        Cond::Conjunction(clauses) => {
            Cond::conjunction(clauses.iter().map(|c| adopt_cond(c, cellsize)).collect())
        }
        Cond::Disjunction(clauses) => {
            Cond::disjunction(clauses.iter().map(|c| adopt_cond(c, cellsize)).collect())
        }
        _ => cond.clone(),
    }
}

fn split_lines_inclusive(s: &[u8]) -> Vec<&[u8]> {
    if s.is_empty() {
        return Vec::new();
    }
    let mut result = Vec::new();
    let mut start = 0;
    for (i, &b) in s.iter().enumerate() {
        if b == b'\n' {
            result.push(&s[start..=i]);
            start = i + 1;
        }
    }
    if start < s.len() {
        result.push(&s[start..]);
    }
    result
}

#[cfg(test)]
mod tests {
    use super::*;

    fn generate_c(node: &Node, cellsize: u32) -> String {
        let gen = Generator::new(cellsize, false, None, false);
        let mut out = Vec::new();
        gen.generate(node, &mut out).unwrap();
        String::from_utf8(out).unwrap()
    }

    #[test]
    fn empty_program() {
        let node = Node::Program { children: vec![] };
        let output = generate_c(&node, 8);
        assert!(output.contains("int main(void)"));
        assert!(output.contains("return 0;"));
        assert!(output.contains("uint8_t"));
    }

    #[test]
    fn cellsize_16() {
        let node = Node::Program { children: vec![] };
        let output = generate_c(&node, 16);
        assert!(output.contains("uint16_t"));
    }

    #[test]
    fn cellsize_32() {
        let node = Node::Program { children: vec![] };
        let output = generate_c(&node, 32);
        assert!(output.contains("uint32_t"));
    }

    #[test]
    fn set_memory_increment() {
        let node = Node::Program {
            children: vec![Node::adjust_memory_by(0, 1)],
        };
        let output = generate_c(&node, 8);
        assert!(output.contains("++p[0]"));
    }

    #[test]
    fn set_memory_decrement() {
        let node = Node::Program {
            children: vec![Node::adjust_memory_by(0, -1)],
        };
        let output = generate_c(&node, 8);
        assert!(output.contains("--p[0]"));
    }

    #[test]
    fn set_memory_absolute() {
        let node = Node::Program {
            children: vec![Node::SetMemory {
                offset: 0,
                value: Expr::Int(42),
            }],
        };
        let output = generate_c(&node, 8);
        assert!(output.contains("p[0] = 42;"));
    }

    #[test]
    fn move_pointer() {
        let node = Node::Program {
            children: vec![Node::MovePointer { offset: 3 }],
        };
        let output = generate_c(&node, 8);
        assert!(output.contains("p += 3;"));
    }

    #[test]
    fn input_generates_getc() {
        let node = Node::Program {
            children: vec![Node::Input { offset: 0 }],
        };
        let output = generate_c(&node, 8);
        assert!(output.contains("GETC()"));
        assert!(output.contains("#define GETC"));
    }

    #[test]
    fn output_generates_putc() {
        let node = Node::Program {
            children: vec![Node::Output { expr: Expr::mem(0) }],
        };
        let output = generate_c(&node, 8);
        assert!(output.contains("PUTC("));
        assert!(output.contains("#define PUTC"));
    }

    #[test]
    fn output_const_generates_puts() {
        let node = Node::Program {
            children: vec![Node::OutputConst {
                s: b"Hello".to_vec(),
            }],
        };
        let output = generate_c(&node, 8);
        assert!(output.contains("PUTS(\"Hello\")"));
        assert!(output.contains("#define PUTS"));
    }

    #[test]
    fn output_const_escaping() {
        let node = Node::Program {
            children: vec![Node::OutputConst {
                s: vec![0, 9, 10, 13, 34, 92],
            }],
        };
        let output = generate_c(&node, 8);
        assert!(output.contains("\\0"));
        assert!(output.contains("\\t"));
        assert!(output.contains("\\n"));
        assert!(output.contains("\\r"));
        assert!(output.contains("\\\""));
        assert!(output.contains("\\\\"));
    }

    #[test]
    fn while_loop() {
        let node = Node::Program {
            children: vec![Node::While {
                cond: Cond::MemNotEqual(0, 0),
                children: vec![Node::adjust_memory_by(0, -1)],
            }],
        };
        let output = generate_c(&node, 8);
        assert!(output.contains("while (p[0])"));
    }

    #[test]
    fn infinite_loop() {
        let node = Node::Program {
            children: vec![Node::While {
                cond: Cond::Always,
                children: vec![],
            }],
        };
        let output = generate_c(&node, 8);
        assert!(output.contains("while (1);"));
        assert!(!output.contains("return 0;"));
    }

    #[test]
    fn if_node() {
        let node = Node::Program {
            children: vec![Node::If {
                cond: Cond::MemNotEqual(0, 0),
                children: vec![Node::adjust_memory_by(1, 1)],
            }],
        };
        let output = generate_c(&node, 8);
        assert!(output.contains("if (p[0])"));
    }

    #[test]
    fn seek_memory() {
        let node = Node::Program {
            children: vec![Node::SeekMemory {
                target: 0,
                stride: 1,
                value: 0,
            }],
        };
        let output = generate_c(&node, 8);
        assert!(output.contains("while (p[0] != 0) ++p;"));
    }

    #[test]
    fn no_unused_macros() {
        let node = Node::Program {
            children: vec![Node::adjust_memory_by(0, 1)],
        };
        let output = generate_c(&node, 8);
        assert!(!output.contains("#define GETC"));
        assert!(!output.contains("#define PUTC"));
        assert!(!output.contains("#define PUTS"));
    }

    #[test]
    fn split_lines_inclusive_basic() {
        let lines = split_lines_inclusive(b"abc\ndef");
        assert_eq!(lines, vec![b"abc\n".as_ref(), b"def".as_ref()]);
    }

    #[test]
    fn split_lines_inclusive_empty() {
        assert!(split_lines_inclusive(b"").is_empty());
    }

    #[test]
    fn split_lines_inclusive_trailing_newline() {
        let lines = split_lines_inclusive(b"abc\n");
        assert_eq!(lines, vec![b"abc\n".as_ref()]);
    }

    #[test]
    fn addslashes_printable() {
        assert_eq!(Addslashes(b"ABC").to_string(), "ABC");
    }

    #[test]
    fn addslashes_special() {
        assert_eq!(Addslashes(b"\0").to_string(), "\\0");
        assert_eq!(Addslashes(b"\t").to_string(), "\\t");
        assert_eq!(Addslashes(b"\n").to_string(), "\\n");
        assert_eq!(Addslashes(b"\\").to_string(), "\\\\");
    }

    #[test]
    fn addslashes_nonprintable() {
        assert_eq!(Addslashes(&[128]).to_string(), "\\200");
        assert_eq!(Addslashes(&[255]).to_string(), "\\377");
    }

    #[test]
    fn cexpr_display() {
        assert_eq!(CExpr(&Expr::Int(42)).to_string(), "42");
        assert_eq!(CExpr(&Expr::mem(0)).to_string(), "p[0]");
    }

    #[test]
    fn ccond_display() {
        assert_eq!(CCond(&Cond::Always).to_string(), "1");
        assert_eq!(CCond(&Cond::Never).to_string(), "0");
        assert_eq!(CCond(&Cond::MemNotEqual(0, 0)).to_string(), "p[0]");
        assert_eq!(CCond(&Cond::MemEqual(0, 0)).to_string(), "!p[0]");
    }

    #[test]
    fn format_adjust_display() {
        assert_eq!(FormatAdjust("p", &Expr::Int(0)).to_string(), "");
        assert_eq!(FormatAdjust("p", &Expr::Int(1)).to_string(), "++p");
        assert_eq!(FormatAdjust("p", &Expr::Int(-1)).to_string(), "--p");
        assert_eq!(FormatAdjust("p[0]", &Expr::Int(3)).to_string(), "p[0] += 3");
    }
}
